"""Ecosystem ignore templates, the marker files that imply them, and first-run bootstrap."""

from __future__ import annotations

import contextlib
import warnings
from dataclasses import dataclass
from importlib import resources
from pathlib import Path

from synapse.core.config.ignores import ConfigScope
from synapse.core.config.settings import (
    AUTO_IGNORE_BOOTSTRAP_KEY,
    BOOTSTRAP_ENV_OPT_OUT,
    IGNORE_FILE_HEADER,
    IgnoreWriteResult,
    auto_ignore_bootstrap_enabled,
    synapseignore_path,
    write_ignore_file,
)

_TEMPLATE_ROOT = resources.files("synapse.core.config") / "ignore_templates"
_TEMPLATE_SUFFIX = ".synapseignore"
_INIT_ORIGIN = "# Generated by `synapse ignore init`.\n"
_BOOTSTRAP_ORIGIN = (
    "# Created automatically on first index. Turn that off with "
    f"{BOOTSTRAP_ENV_OPT_OUT}=1\n"
    f'# or "{AUTO_IGNORE_BOOTSTRAP_KEY}": false in .synapse/config.json.\n'
)


@dataclass(frozen=True, slots=True)
class IgnorePreset:
    """One ecosystem ignore template and the marker files that imply it."""

    id: str
    display_name: str
    markers: tuple[str, ...]
    auto_selectable: bool = True


PRESETS: dict[str, IgnorePreset] = {
    preset.id: preset
    for preset in (
        IgnorePreset("node", "Node.js", ("package.json", "pnpm-lock.yaml", "yarn.lock")),
        IgnorePreset(
            "dotnet",
            ".NET",
            ("*.sln", "*.csproj", "*.fsproj", "Directory.Build.props"),
        ),
        IgnorePreset("java", "Java / Kotlin", ("pom.xml", "build.gradle", "build.gradle.kts")),
        IgnorePreset("python", "Python", ("pyproject.toml", "setup.py", "requirements.txt")),
        IgnorePreset("go", "Go", ("go.mod",)),
        IgnorePreset("rust", "Rust", ("Cargo.toml",)),
        IgnorePreset("swift", "Swift / Xcode", ("Package.swift", "*.xcodeproj", "Podfile")),
        IgnorePreset("android", "Android", ("settings.gradle", "settings.gradle.kts")),
        IgnorePreset("php", "PHP", ("composer.json",)),
        IgnorePreset("ruby", "Ruby", ("Gemfile",)),
        IgnorePreset("unity", "Unity", ("ProjectSettings/ProjectVersion.txt",)),
        IgnorePreset("ml", "Machine learning", ("*.ipynb", "environment.yml")),
        IgnorePreset("terraform", "Terraform", ("*.tf",)),
        # Mostly covered by the built-in defaults already, so never auto-selected.
        IgnorePreset("editors", "Editors and OS", (), auto_selectable=False),
    )
}


def preset_patterns(preset_id: str) -> tuple[str, ...]:
    """Return one preset's patterns, in template order."""
    if preset_id not in PRESETS:
        known = ", ".join(sorted(PRESETS))
        msg = f"Unknown ignore preset {preset_id!r}. Available presets: {known}."
        raise ValueError(msg)

    text = (_TEMPLATE_ROOT / f"{preset_id}{_TEMPLATE_SUFFIX}").read_text(encoding="utf-8")
    return tuple(
        stripped
        for line in text.splitlines()
        if (stripped := line.strip()) and not stripped.startswith("#")
    )


def _matches_marker(directory: Path, marker: str) -> bool:
    try:
        return any(directory.glob(marker))
    except OSError:
        return False


def detect_presets(workspace_root: Path) -> tuple[str, ...]:
    """Return the auto-selectable presets whose marker files appear near the workspace root.

    Only the root and its immediate subdirectories are scanned — enough for the monorepo case
    (`packages/*/package.json`) without ever walking the tree, which matters because this runs
    during workspace initialization.
    """
    directories = [workspace_root]
    with contextlib.suppress(OSError):
        directories.extend(
            child for child in workspace_root.iterdir() if child.is_dir() and not child.is_symlink()
        )

    return tuple(
        preset.id
        for preset in PRESETS.values()
        if preset.auto_selectable
        and any(
            _matches_marker(directory, marker)
            for marker in preset.markers
            for directory in directories
        )
    )


def render_preset_file(
    presets: tuple[str, ...], *, origin: str = _INIT_ORIGIN
) -> tuple[str, list[str]]:
    """Return the header and pattern lines for a generated ignore file.

    Each preset's patterns sit under a comment naming it, purely so the file reads well; the
    comments carry no meaning for the matcher.
    """
    header = f"{IGNORE_FILE_HEADER}{origin}# Presets: {', '.join(presets)}.\n"
    lines: list[str] = []
    for preset_id in presets:
        if lines:
            lines.append("")
        lines.append(f"# {PRESETS[preset_id].display_name}")
        lines.extend(preset_patterns(preset_id))
    return header, lines


def bootstrap_project_ignores(workspace_root: Path) -> IgnoreWriteResult | None:
    """Create .synapseignore from the detected ecosystems, once, during first-run init.

    Returns None whenever nothing was written. An existing file is never touched: from the
    moment it exists it belongs to the repository, not to Synapse. Failing to write one must
    never fail an index, so every filesystem error degrades to a warning.
    """
    if synapseignore_path(workspace_root).exists():
        return None
    if not auto_ignore_bootstrap_enabled(workspace_root):
        return None

    try:
        presets = detect_presets(workspace_root)
        if not presets:
            return None
        header, lines = render_preset_file(presets, origin=_BOOTSTRAP_ORIGIN)
        return write_ignore_file(workspace_root, lines, scope=ConfigScope.PROJECT, header=header)
    except OSError as exc:
        warnings.warn(f"Could not create {synapseignore_path(workspace_root)}: {exc}", stacklevel=2)
        return None
