"""Agent adapter metadata, MCP rendering, instructions, and managed skills."""

from synapse.cli.adapters.instructions import (
    ADAPTERS_ROOT,
    BEGIN_MARKER,
    END_MARKER,
    GLOBAL_INSTRUCTION_SNIPPET,
    PROJECT_INSTRUCTION_SNIPPET,
    global_snippet,
    install_global_instruction,
    install_instruction_snippet,
    install_instructions,
    project_instruction_path,
    project_snippet,
    remove_global_instruction,
    remove_instruction_snippet,
    remove_instructions,
    resolve_global_instruction_path,
    resolve_instruction_path,
)
from synapse.cli.adapters.model import (
    AgentAdapter,
    ConfigFormat,
    ContainerShape,
    InstructionInstallResult,
    InstructionMode,
    InstructionTarget,
    McpTarget,
    PathSpec,
    PayloadStyle,
    SkillInstallResult,
)
from synapse.cli.adapters.paths import resolve_project_path, resolve_user_path
from synapse.cli.adapters.registry import ADAPTERS, adapter_choices, get_adapter
from synapse.cli.adapters.render import build_server_entry, render_mcp_config, server_command
from synapse.cli.adapters.skills import (
    MANAGED_SKILL_MARKER,
    MANAGED_SKILL_RELATIVE_PATHS,
    SKILLS_ROOT,
    SYNAPSE_SKILL,
    install_global_skill,
    install_project_skill,
    install_skill,
    remove_global_skill,
    remove_project_skill,
    remove_skill,
    resolve_global_skill_path,
    resolve_project_skill_path,
)

__all__ = [
    "ADAPTERS",
    "ADAPTERS_ROOT",
    "BEGIN_MARKER",
    "END_MARKER",
    "GLOBAL_INSTRUCTION_SNIPPET",
    "MANAGED_SKILL_MARKER",
    "MANAGED_SKILL_RELATIVE_PATHS",
    "PROJECT_INSTRUCTION_SNIPPET",
    "SKILLS_ROOT",
    "SYNAPSE_SKILL",
    "AgentAdapter",
    "ConfigFormat",
    "ContainerShape",
    "InstructionInstallResult",
    "InstructionMode",
    "InstructionTarget",
    "McpTarget",
    "PathSpec",
    "PayloadStyle",
    "SkillInstallResult",
    "adapter_choices",
    "build_server_entry",
    "get_adapter",
    "global_snippet",
    "install_global_instruction",
    "install_global_skill",
    "install_instruction_snippet",
    "install_instructions",
    "install_project_skill",
    "install_skill",
    "project_instruction_path",
    "project_snippet",
    "remove_global_instruction",
    "remove_global_skill",
    "remove_instruction_snippet",
    "remove_instructions",
    "remove_project_skill",
    "remove_skill",
    "render_mcp_config",
    "resolve_global_instruction_path",
    "resolve_global_skill_path",
    "resolve_instruction_path",
    "resolve_project_path",
    "resolve_project_skill_path",
    "resolve_user_path",
    "server_command",
]
